# Pandas

Pandas is a fundamental library for data manipulation and analysis in Python. It provides high-performance, easy-to-use data structures like Series and DataFrames. A Series is a one-dimensional array-like object,
while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure
with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\anash\desktop\python basics\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
## Introduction to pandas
import pandas as pd

# Series

In [3]:
'''
Series 
A panda series is like a 1 Dimensional Array like object that can hold any datatype
similar to a column in a table'''

import pandas as pd
data=[1,2,3,4,5]

series = pd.Series(data)
print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
data_dict = { 'a':1 , 'b':2 , 'c':3}
series_dict =pd.Series(data_dict)

print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

# Data Frames

In [6]:
## DataFrames
## Creating a Dataframe from a dictionary of lists

data ={
    'Name': ['Anas','John','Jack'],
    'Age':[19,20,25],
    'City':['Nagpur','Los Angeles','New York']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York
<class 'pandas.core.frame.DataFrame'>

In [7]:
## Creating a Data Frame from a list of Dictionaries

data1 =[
    {'Name':'Anas' , 'Age' : 19 , 'City': 'Dubai'},
    {'Name':'Hamdan' , 'Age' : 15 , 'City': 'Sharjah'},
    {'Name':'Sam' , 'Age' : 30 , 'City': 'New York'},
    {'Name':'Samadhnya' , 'Age' : 25 , 'City': 'Los Angeles'},  
]
df = pd.DataFrame(data1)
print(df)
print(type(df))

        Name  Age         City
0       Anas   19        Dubai
1     Hamdan   15      Sharjah
2        Sam   30     New York
3  Samadhnya   25  Los Angeles
<class 'pandas.core.frame.DataFrame'>

In [8]:
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,Unnamed: 5,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,Motorcycles
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,Motorcycles
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,Motorcycles
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,Motorcycles

In [9]:
df.tail(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,Unnamed: 5,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE
19,10329,42,100.00,1,4396.14,11/15/2004 0:00,Shipped,4,11,2004,Motorcycles
20,10341,41,100.00,9,7737.93,11/24/2004 0:00,Shipped,4,11,2004,Motorcycles
21,10361,20,72.55,13,1451.00,12/17/2004 0:00,Shipped,4,12,2004,Motorcycles
22,10375,21,34.91,12,733.11,2/3/2005 0:00,Shipped,1,2,2005,Motorcycles
23,10388,42,76.36,4,3207.12,3/3/2005 0:00,Shipped,1,3,2005,Motorcycles

In [10]:
## Accesing data from Data Frames
df = pd.DataFrame(data)

In [11]:
df

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [12]:
df['Name']

0    Anas
1    John
2    Jack
Name: Name, dtype: object

In [ ]:
df.loc[0]  ## Accessing According to Row Index(loc)

Name      Anas
Age         19
City    Nagpur
Name: 0, dtype: object

In [14]:
df.loc[0][0]

C:\Users\anash\AppData\Local\Temp\ipykernel_17816\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Anas'

In [ ]:
df.iloc[0]  ## Accesing According to Column Index(iloc)

Name      Anas
Age         19
City    Nagpur
Name: 0, dtype: object

In [17]:
df.iloc[1][2]

C:\Users\anash\AppData\Local\Temp\ipykernel_17816\65333983.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][2]

'Los Angeles'

In [18]:
df

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [ ]:
df.at[1,'Age']  ## Accesing elements According to Specific Location

np.int64(20)

In [ ]:
df.at[2,'Age']

np.int64(25)

In [21]:
df.at[2,'Name']

'Jack'

In [22]:
df

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [23]:
## Data Manipulation with Data Frames
df

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [31]:
## Adding a Column 
df['Salary'] = [50000,40000,35000]
df

   Name  Age         City  Salary
0  Anas   19       Nagpur   50000
1  John   20  Los Angeles   40000
2  Jack   25     New York   35000

In [32]:
## Removing a Column
df.drop('Salary',axis=1)

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [33]:
df

   Name  Age         City  Salary
0  Anas   19       Nagpur   50000
1  John   20  Los Angeles   40000
2  Jack   25     New York   35000

In [34]:
## to remove an column element permanently 
df.drop('Salary',axis=1,inplace=True)

In [35]:
df

   Name  Age         City
0  Anas   19       Nagpur
1  John   20  Los Angeles
2  Jack   25     New York

In [36]:
## Add Age to the column

df['Age'] = df['Age']+1
df

   Name  Age         City
0  Anas   20       Nagpur
1  John   21  Los Angeles
2  Jack   26     New York

In [37]:
df.drop(0,inplace=True)

In [38]:
df

   Name  Age         City
1  John   21  Los Angeles
2  Jack   26     New York

In [40]:
## Display Daa Types of each column 
print("Data Types:\n", df.dtypes)

## Describe the DataFrame
print("Statistical summary: \n",df.describe())

Data Types:
 Name    object
Age      int64
City    object
dtype: object
Statistical summary:
              Age
count   2.000000
mean   23.500000
std     3.535534
min    21.000000
25%    22.250000
50%    23.500000
75%    24.750000
max    26.000000