# Data Manipulation With Pandas And Numpy

Building upon the basics from the previous sections, we will now explore more advanced data manipulation and mathematical operations combining Pandas operations and Numpy capabilities. Key techniques included here are:
Filtering
Handling missing values
Grouping
Applying functions.

In [76]:
import pandas as pd
import numpy as np

# Creating a Sample DataFrame

In [77]:
data = {
    'Name': ['Anas', 'John', 'Jack', 'Sam', 'Hamdan'],
    'Age': [19, 20, 25, 30, 15],
    'Salary': [50000, 40000, 35000, 60000, 20000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
}
df = pd.DataFrame(data)
df

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [78]:
df.head(5)

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [79]:
df.tail(5)

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [80]:
df_csv = pd.read_csv("sales_data_sample.csv")
df_csv.drop('ORDERLINENUMBER',axis=1,inplace=True)
df_csv.drop('QUANTITYORDERED',axis=1,inplace=True)
df_csv.drop('QTR_ID',axis=1,inplace=True)
df_csv.drop('MONTH_ID',axis=1,inplace=True)
df_csv.drop('YEAR_ID',axis=1,inplace=True)
df_csv.drop('ORDERNUMBER',axis=1,inplace=True)
df_csv.drop('STATUS',axis=1,inplace=True)

In [81]:
df_csv.head(5)

   PRICEEACH    SALES       Unnamed: 5  PRODUCTLINE
0      95.70  2871.00   2/24/2003 0:00  Motorcycles
1      81.35  2765.90    5/7/2003 0:00  Motorcycles
2      94.74      NaN    7/1/2003 0:00  Motorcycles
3      83.26  3746.70   8/25/2003 0:00  Motorcycles
4     100.00  5205.27  10/10/2003 0:00  Motorcycles

In [82]:
df_csv.tail(5)

    PRICEEACH    SALES       Unnamed: 5  PRODUCTLINE
19     100.00  4396.14  11/15/2004 0:00  Motorcycles
20     100.00  7737.93  11/24/2004 0:00  Motorcycles
21      72.55  1451.00  12/17/2004 0:00  Motorcycles
22      34.91   733.11    2/3/2005 0:00  Motorcycles
23      76.36  3207.12    3/3/2005 0:00  Motorcycles

In [83]:
df.describe()

            Age        Salary
count   5.00000      5.000000
mean   21.80000  41000.000000
std     5.80517  15165.750888
min    15.00000  20000.000000
25%    19.00000  35000.000000
50%    20.00000  40000.000000
75%    25.00000  50000.000000
max    30.00000  60000.000000

# Filtering Data

In [84]:
# Filter people older than 20
df_filtered = df[df['Age'] > 20]
df_filtered

   Name  Age  Salary Department
2  Jack   25   35000         IT
3   Sam   30   60000    Finance

# Handling Missing Values with isnull()

In [85]:
df_csv.isnull().any(axis=0)

PRICEEACH      False
SALES           True
Unnamed: 5     False
PRODUCTLINE    False
dtype: bool

In [86]:
df_csv.isnull().sum() ## represent number of values missing

PRICEEACH      0
SALES          2
Unnamed: 5     0
PRODUCTLINE    0
dtype: int64

In [87]:
df_csv.isnull()

    PRICEEACH  SALES  Unnamed: 5  PRODUCTLINE
0       False  False       False        False
1       False  False       False        False
2       False   True       False        False
3       False  False       False        False
4       False  False       False        False
5       False  False       False        False
6       False  False       False        False
7       False   True       False        False
8       False  False       False        False
9       False  False       False        False
10      False  False       False        False
11      False  False       False        False
12      False  False       False        False
13      False  False       False        False
14      False  False       False        False
15      False  False       False        False
16      False  False       False        False
17      False  False       False        False
18      False  False       False        False
19      False  False       False        False
20      False  False       False        False
21      False  False       False        False
22      False  False       False        False
23      False  False       False        False

In [88]:
df_filled = df_csv.fillna(0)
df_filled.head(5)

   PRICEEACH    SALES       Unnamed: 5  PRODUCTLINE
0      95.70  2871.00   2/24/2003 0:00  Motorcycles
1      81.35  2765.90    5/7/2003 0:00  Motorcycles
2      94.74     0.00    7/1/2003 0:00  Motorcycles
3      83.26  3746.70   8/25/2003 0:00  Motorcycles
4     100.00  5205.27  10/10/2003 0:00  Motorcycles

In [89]:
## Handling Missing values with the mean of the column

df_csv['Sales_fillNA'] = df_csv['SALES'].fillna(df_csv['SALES'].mean())   
## Sales_fillna gets filled with the mean 3534.53xx for each Sales value missing
df_csv.head(10)

   PRICEEACH    SALES       Unnamed: 5  PRODUCTLINE  Sales_fillNA
0      95.70  2871.00   2/24/2003 0:00  Motorcycles   2871.000000
1      81.35  2765.90    5/7/2003 0:00  Motorcycles   2765.900000
2      94.74      NaN    7/1/2003 0:00  Motorcycles   3534.531818
3      83.26  3746.70   8/25/2003 0:00  Motorcycles   3746.700000
4     100.00  5205.27  10/10/2003 0:00  Motorcycles   5205.270000
5      96.66  3479.76  10/28/2003 0:00  Motorcycles   3479.760000
6      86.13  2497.77  11/11/2003 0:00  Motorcycles   2497.770000
7     100.00      NaN  11/18/2003 0:00  Motorcycles   3534.531818
8      98.57  2168.54   12/1/2003 0:00  Motorcycles   2168.540000
9     100.00  4708.44   1/15/2004 0:00  Motorcycles   4708.440000

In [90]:
df_csv.dtypes

PRICEEACH       float64
SALES           float64
Unnamed: 5       object
PRODUCTLINE      object
Sales_fillNA    float64
dtype: object

In [91]:
## Renaming Columns 

df_csv = df_csv.rename(columns = {'Unnamed: 5' : 'Sales Date' }) ## IMP TO GIVE IN KEY VALUE PAIRS
df_csv.head(5)

   PRICEEACH    SALES       Sales Date  PRODUCTLINE  Sales_fillNA
0      95.70  2871.00   2/24/2003 0:00  Motorcycles   2871.000000
1      81.35  2765.90    5/7/2003 0:00  Motorcycles   2765.900000
2      94.74      NaN    7/1/2003 0:00  Motorcycles   3534.531818
3      83.26  3746.70   8/25/2003 0:00  Motorcycles   3746.700000
4     100.00  5205.27  10/10/2003 0:00  Motorcycles   5205.270000

In [92]:
df_csv.head(5)

   PRICEEACH    SALES       Sales Date  PRODUCTLINE  Sales_fillNA
0      95.70  2871.00   2/24/2003 0:00  Motorcycles   2871.000000
1      81.35  2765.90    5/7/2003 0:00  Motorcycles   2765.900000
2      94.74      NaN    7/1/2003 0:00  Motorcycles   3534.531818
3      83.26  3746.70   8/25/2003 0:00  Motorcycles   3746.700000
4     100.00  5205.27  10/10/2003 0:00  Motorcycles   5205.270000

In [93]:
df_csv.dtypes

PRICEEACH       float64
SALES           float64
Sales Date       object
PRODUCTLINE      object
Sales_fillNA    float64
dtype: object

# Changing Data Types

In [94]:
## Works for non missingg values 
df_csv['PriceEach_new'] = df_csv['PRICEEACH'].astype(int)

In [95]:
## If there are missing values in the particular field
df_csv.loc[[2, 5, 8], 'PRICEEACH'] = np.nan  ## Creating missing values at 2 5 and 8th index 

## Changing datatypes of such first we add values on the missing fields and then change the datatypes
df_csv['PRICEEACH_new'] = df_csv['PRICEEACH'].fillna(df_csv['PRICEEACH'].mean()).astype(int)

In [96]:
df_csv.head(5)

,PRICEEACH,SALES,Sales Date,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new
0,95.70,2871.00,2/24/2003 0:00,Motorcycles,2871.000000,95,95
1,81.35,2765.90,5/7/2003 0:00,Motorcycles,2765.900000,81,81
2,NaN,NaN,7/1/2003 0:00,Motorcycles,3534.531818,94,91
3,83.26,3746.70,8/25/2003 0:00,Motorcycles,3746.700000,83,83
4,100.00,5205.27,10/10/2003 0:00,Motorcycles,5205.270000,100,100

In [97]:
#df_csv['New Sales'] = df_csv['SALES'].apply(lambda x:np.nan)  ## Created a completely Empty Column
df_csv['New Sales'] = df_csv['SALES'].apply(lambda x: x/1000)  ## Creation of a column with Thousands converted
df_csv.head(5)

,PRICEEACH,SALES,Sales Date,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new,New Sales
0,95.70,2871.00,2/24/2003 0:00,Motorcycles,2871.000000,95,95,2.87100
1,81.35,2765.90,5/7/2003 0:00,Motorcycles,2765.900000,81,81,2.76590
2,NaN,NaN,7/1/2003 0:00,Motorcycles,3534.531818,94,91,NaN
3,83.26,3746.70,8/25/2003 0:00,Motorcycles,3746.700000,83,83,3.74670
4,100.00,5205.27,10/10/2003 0:00,Motorcycles,5205.270000,100,100,5.20527

# Data Aggregating And Grouping

In [98]:
df = df_csv.head(5)
df

,PRICEEACH,SALES,Sales Date,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new,New Sales
0,95.70,2871.00,2/24/2003 0:00,Motorcycles,2871.000000,95,95,2.87100
1,81.35,2765.90,5/7/2003 0:00,Motorcycles,2765.900000,81,81,2.76590
2,NaN,NaN,7/1/2003 0:00,Motorcycles,3534.531818,94,91,NaN
3,83.26,3746.70,8/25/2003 0:00,Motorcycles,3746.700000,83,83,3.74670
4,100.00,5205.27,10/10/2003 0:00,Motorcycles,5205.270000,100,100,5.20527

In [99]:
df['Category'] = ['Group1','Group3','Group1','Group2','Group3']

C:\Users\anash\AppData\Local\Temp\ipykernel_30628\2399606222.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = ['Group1','Group3','Group1','Group2','Group3']

In [100]:
df['SALES'] = df['SALES'].fillna(df['SALES'].mean())

C:\Users\anash\AppData\Local\Temp\ipykernel_30628\1229962291.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SALES'] = df['SALES'].fillna(df['SALES'].mean())

In [101]:
## Data Grouping
grouped_mean = df.groupby('Category')['SALES'].mean()
print(grouped_mean)

Category
Group1    3259.10875
Group2    3746.70000
Group3    3985.58500
Name: SALES, dtype: float64

In [102]:
## According to multiple categorical values 
category_col = df.pop('Category')  ## Moving the Category Column to the front index = 0
df.insert(0, 'Category', category_col)
category_col = df.pop('SALES')
df.insert(1,'SALES',category_col)
df.loc[[1,2,4],'PRODUCTLINE'] = 'CAR'
df

,Category,SALES,PRICEEACH,Sales Date,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new,New Sales
0,Group1,2871.0000,95.70,2/24/2003 0:00,Motorcycles,2871.000000,95,95,2.87100
1,Group3,2765.9000,81.35,5/7/2003 0:00,CAR,2765.900000,81,81,2.76590
2,Group1,3647.2175,NaN,7/1/2003 0:00,CAR,3534.531818,94,91,NaN
3,Group2,3746.7000,83.26,8/25/2003 0:00,Motorcycles,3746.700000,83,83,3.74670
4,Group3,5205.2700,100.00,10/10/2003 0:00,CAR,5205.270000,100,100,5.20527

In [103]:
grouped_sum = df.groupby(['Category','PRODUCTLINE'])['SALES'].sum()
print(grouped_sum)

Category  PRODUCTLINE
Group1    CAR            3647.2175
          Motorcycles    2871.0000
Group2    Motorcycles    3746.7000
Group3    CAR            7971.1700
Name: SALES, dtype: float64

In [104]:
grouped_mean = df.groupby(['Category','PRODUCTLINE'])['SALES'].mean()
print(grouped_mean)

Category  PRODUCTLINE
Group1    CAR            3647.2175
          Motorcycles    2871.0000
Group2    Motorcycles    3746.7000
Group3    CAR            3985.5850
Name: SALES, dtype: float64

In [108]:
## Aggregate Multiple Functions 
grouped_agg = df.groupby('PRODUCTLINE')['SALES'].agg(['mean','sum','count']) 
print(grouped_agg)

                    mean         sum  count
PRODUCTLINE
CAR          3872.795833  11618.3875      3
Motorcycles  3308.850000   6617.7000      2

# Merging And Joining Data Frames

In [111]:
# Create Sample DATA FRAMES
df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})

In [112]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [113]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:
## Merging on the basis of the columns('Key' column)

pd.merge(df1,df2,on='Key',how='inner')  ## inner join causes same element from key column for merge

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [115]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [116]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN