# Data Manipulation With Pandas And Numpy

Building upon the basics from the previous sections, we will now explore more advanced data manipulation and mathematical operations combining Pandas operations and Numpy capabilities. Key techniques included here are:
Filtering
Handling missing values
Grouping
Applying functions.

In [1]:
import pandas as pd
import numpy as np

# Creating a Sample DataFrame

In [2]:
data = {
    'Name': ['Anas', 'John', 'Jack', 'Sam', 'Hamdan'],
    'Age': [19, 20, 25, 30, 15],
    'Salary': [50000, 40000, 35000, 60000, 20000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
}
df = pd.DataFrame(data)
df

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [3]:
df.head(5)

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [4]:
df.tail(5)

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

In [5]:
df_csv = pd.read_csv("sales_data_sample.csv")
df_csv.drop('ORDERLINENUMBER',axis=1,inplace=True)
df_csv.drop('QUANTITYORDERED',axis=1,inplace=True)
df_csv.drop('QTR_ID',axis=1,inplace=True)
df_csv.drop('MONTH_ID',axis=1,inplace=True)
df_csv.drop('YEAR_ID',axis=1,inplace=True)

In [6]:
df_csv.head(5)

   ORDERNUMBER  PRICEEACH    SALES       Unnamed: 5   STATUS  PRODUCTLINE
0        10107      95.70  2871.00   2/24/2003 0:00  Shipped  Motorcycles
1        10121      81.35  2765.90    5/7/2003 0:00  Shipped  Motorcycles
2        10134      94.74      NaN    7/1/2003 0:00  Shipped  Motorcycles
3        10145      83.26  3746.70   8/25/2003 0:00  Shipped  Motorcycles
4        10159     100.00  5205.27  10/10/2003 0:00  Shipped  Motorcycles

In [7]:
df_csv.tail(5)

    ORDERNUMBER  PRICEEACH    SALES       Unnamed: 5   STATUS  PRODUCTLINE
19        10329     100.00  4396.14  11/15/2004 0:00  Shipped  Motorcycles
20        10341     100.00  7737.93  11/24/2004 0:00  Shipped  Motorcycles
21        10361      72.55  1451.00  12/17/2004 0:00  Shipped  Motorcycles
22        10375      34.91   733.11    2/3/2005 0:00  Shipped  Motorcycles
23        10388      76.36  3207.12    3/3/2005 0:00  Shipped  Motorcycles

In [8]:
df.describe()

            Age        Salary
count   5.00000      5.000000
mean   21.80000  41000.000000
std     5.80517  15165.750888
min    15.00000  20000.000000
25%    19.00000  35000.000000
50%    20.00000  40000.000000
75%    25.00000  50000.000000
max    30.00000  60000.000000

# Filtering Data

In [9]:
# Filter people older than 20
df_filtered = df[df['Age'] > 20]
df_filtered

   Name  Age  Salary Department
2  Jack   25   35000         IT
3   Sam   30   60000    Finance

# Handling Missing Values with isnull()

In [10]:
df_csv.isnull().any(axis=0)

ORDERNUMBER    False
PRICEEACH      False
SALES           True
Unnamed: 5     False
STATUS         False
PRODUCTLINE    False
dtype: bool

In [11]:
df_csv.isnull().sum() ## represent number of values missing

ORDERNUMBER    0
PRICEEACH      0
SALES          2
Unnamed: 5     0
STATUS         0
PRODUCTLINE    0
dtype: int64

In [12]:
df_csv.isnull()

    ORDERNUMBER  PRICEEACH  SALES  Unnamed: 5  STATUS  PRODUCTLINE
0         False      False  False       False   False        False
1         False      False  False       False   False        False
2         False      False   True       False   False        False
3         False      False  False       False   False        False
4         False      False  False       False   False        False
5         False      False  False       False   False        False
6         False      False  False       False   False        False
7         False      False   True       False   False        False
8         False      False  False       False   False        False
9         False      False  False       False   False        False
10        False      False  False       False   False        False
11        False      False  False       False   False        False
12        False      False  False       False   False        False
13        False      False  False       False   False        False
14        False      False  False       False   False        False
15        False      False  False       False   False        False
16        False      False  False       False   False        False
17        False      False  False       False   False        False
18        False      False  False       False   False        False
19        False      False  False       False   False        False
20        False      False  False       False   False        False
21        False      False  False       False   False        False
22        False      False  False       False   False        False
23        False      False  False       False   False        False

In [13]:
df_filled = df_csv.fillna(0)
df_filled.head(5)

   ORDERNUMBER  PRICEEACH    SALES       Unnamed: 5   STATUS  PRODUCTLINE
0        10107      95.70  2871.00   2/24/2003 0:00  Shipped  Motorcycles
1        10121      81.35  2765.90    5/7/2003 0:00  Shipped  Motorcycles
2        10134      94.74     0.00    7/1/2003 0:00  Shipped  Motorcycles
3        10145      83.26  3746.70   8/25/2003 0:00  Shipped  Motorcycles
4        10159     100.00  5205.27  10/10/2003 0:00  Shipped  Motorcycles

In [14]:
## Handling Missing values with the mean of the column

df_csv['Sales_fillNA'] = df_csv['SALES'].fillna(df_csv['SALES'].mean())   
## Sales_fillna gets filled with the mean 3534.53xx for each Sales value missing
df_csv.head(10)

,ORDERNUMBER,PRICEEACH,SALES,Unnamed: 5,STATUS,PRODUCTLINE,Sales_fillNA
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000
2,10134,94.74,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000
5,10168,96.66,3479.76,10/28/2003 0:00,Shipped,Motorcycles,3479.760000
6,10180,86.13,2497.77,11/11/2003 0:00,Shipped,Motorcycles,2497.770000
7,10188,100.00,NaN,11/18/2003 0:00,Shipped,Motorcycles,3534.531818
8,10201,98.57,2168.54,12/1/2003 0:00,Shipped,Motorcycles,2168.540000
9,10211,100.00,4708.44,1/15/2004 0:00,Shipped,Motorcycles,4708.440000

In [15]:
df_csv.dtypes

ORDERNUMBER       int64
PRICEEACH       float64
SALES           float64
Unnamed: 5       object
STATUS           object
PRODUCTLINE      object
Sales_fillNA    float64
dtype: object

In [16]:
## Renaming Columns 

df_csv = df_csv.rename(columns = {'Unnamed: 5' : 'Sales Date' }) ## IMP TO GIVE IN KEY VALUE PAIRS
df_csv.head(5)

,ORDERNUMBER,PRICEEACH,SALES,Sales Date,STATUS,PRODUCTLINE,Sales_fillNA
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000
2,10134,94.74,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000

In [17]:
df_csv.head(5)

,ORDERNUMBER,PRICEEACH,SALES,Sales Date,STATUS,PRODUCTLINE,Sales_fillNA
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000
2,10134,94.74,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000

In [18]:
df_csv.dtypes

ORDERNUMBER       int64
PRICEEACH       float64
SALES           float64
Sales Date       object
STATUS           object
PRODUCTLINE      object
Sales_fillNA    float64
dtype: object

# Changing Data Types

In [19]:
## Works for non missingg values 
df_csv['PriceEach_new'] = df_csv['PRICEEACH'].astype(int)

In [20]:
## If there are missing values in the particular field
df_csv.loc[[2, 5, 8], 'PRICEEACH'] = np.nan  ## Creating missing values at 2 5 and 8th index 

## Changing datatypes of such first we add values on the missing fields and then change the datatypes
df_csv['PRICEEACH_new'] = df_csv['PRICEEACH'].fillna(df_csv['PRICEEACH'].mean()).astype(int)

In [21]:
df_csv.head(5)

,ORDERNUMBER,PRICEEACH,SALES,Sales Date,STATUS,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000,95,95
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000,81,81
2,10134,NaN,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818,94,91
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000,83,83
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000,100,100

In [22]:
#df_csv['New Sales'] = df_csv['SALES'].apply(lambda x:np.nan)  ## Created a completely Empty Column
df_csv['New Sales'] = df_csv['SALES'].apply(lambda x: x/1000)  ## Creation of a column with Thousands converted
df_csv.head(5)

,ORDERNUMBER,PRICEEACH,SALES,Sales Date,STATUS,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new,New Sales
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000,95,95,2.87100
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000,81,81,2.76590
2,10134,NaN,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818,94,91,NaN
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000,83,83,3.74670
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000,100,100,5.20527

# Data Aggregating And Grouping

In [23]:
df = df_csv
df.head(5)

,ORDERNUMBER,PRICEEACH,SALES,Sales Date,STATUS,PRODUCTLINE,Sales_fillNA,PriceEach_new,PRICEEACH_new,New Sales
0,10107,95.70,2871.00,2/24/2003 0:00,Shipped,Motorcycles,2871.000000,95,95,2.87100
1,10121,81.35,2765.90,5/7/2003 0:00,Shipped,Motorcycles,2765.900000,81,81,2.76590
2,10134,NaN,NaN,7/1/2003 0:00,Shipped,Motorcycles,3534.531818,94,91,NaN
3,10145,83.26,3746.70,8/25/2003 0:00,Shipped,Motorcycles,3746.700000,83,83,3.74670
4,10159,100.00,5205.27,10/10/2003 0:00,Shipped,Motorcycles,5205.270000,100,100,5.20527

In [ ]:
grouped_mean = df.groupby()