# More on Data Manipulation in Pandas

Building upon the basics, we will now explore more advanced data manipulation techniques such as filtering, handling missing values, grouping, and applying functions.

In [1]:
import pandas as pd
import numpy as np

## 1. Creating a Sample DataFrame

In [2]:
data = {
    'Name': ['Anas', 'John', 'Jack', 'Sam', 'Hamdan'],
    'Age': [19, 20, 25, 30, 15],
    'Salary': [50000, 40000, 35000, 60000, 20000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
}
df = pd.DataFrame(data)
df

     Name  Age  Salary Department
0    Anas   19   50000         IT
1    John   20   40000         HR
2    Jack   25   35000         IT
3     Sam   30   60000    Finance
4  Hamdan   15   20000         HR

## 2. Filtering Data (Boolean Indexing)

In [3]:
# Filter people older than 20
df_filtered = df[df['Age'] > 20]
df_filtered

   Name  Age  Salary Department
2  Jack   25   35000         IT
3   Sam   30   60000    Finance

In [4]:
# Filter with multiple conditions (Age > 18 and Department is IT)
df_multi = df[(df['Age'] > 18) & (df['Department'] == 'IT')]
df_multi

   Name  Age  Salary Department
0  Anas   19   50000         IT
2  Jack   25   35000         IT

## 3. Sorting Data

In [5]:
# Sort by Age in descending order
df_sorted = df.sort_values(by='Age', ascending=False)
df_sorted

     Name  Age  Salary Department
3     Sam   30   60000    Finance
2    Jack   25   35000         IT
1    John   20   40000         HR
0    Anas   19   50000         IT
4  Hamdan   15   20000         HR

## 4. Handling Missing Data (NaN values)

In [6]:
# Adding some missing values for demonstration
df_missing = df.copy()
df_missing.loc[1, 'Salary'] = np.nan
df_missing.loc[3, 'Age'] = np.nan
df_missing

     Name   Age   Salary Department
0    Anas  19.0  50000.0         IT
1    John  20.0      NaN         HR
2    Jack  25.0  35000.0         IT
3     Sam   NaN  60000.0    Finance
4  Hamdan  15.0  20000.0         HR

In [7]:
# Check for missing values
df_missing.isna().sum()

Name          0
Age           1
Salary        1
Department    0
dtype: int64

In [8]:
# Drop rows with missing values permanently
df_dropped = df_missing.dropna()
df_dropped

     Name   Age   Salary Department
0    Anas  19.0  50000.0         IT
2    Jack  25.0  35000.0         IT
4  Hamdan  15.0  20000.0         HR

In [9]:
# Fill missing values with a specific value (e.g., mean/median)
df_filled = df_missing.copy()
df_filled['Salary'] = df_filled['Salary'].fillna(df_filled['Salary'].mean())
df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].median())
df_filled

     Name   Age   Salary Department
0    Anas  19.0  50000.0         IT
1    John  20.0  41250.0         HR
2    Jack  25.0  35000.0         IT
3     Sam  19.5  60000.0    Finance
4  Hamdan  15.0  20000.0         HR

## 5. Grouping and Aggregation

In [10]:
# Group by Department and calculate average properties
grouped_df = df.groupby('Department').mean(numeric_only=True).reset_index()
grouped_df

  Department   Age   Salary
0    Finance  30.0  60000.0
1         HR  17.5  30000.0
2         IT  22.0  42500.0

In [11]:
# Applying multiple aggregate functions
agg_df = df.groupby('Department').agg({
    'Salary': ['mean', 'sum'],
    'Age': 'max'
})
agg_df

             Salary        Age
               mean    sum max
Department
Finance     60000.0  60000  30
HR          30000.0  60000  20
IT          42500.0  85000  25

## 6. Applying Functions (`apply`)

In [12]:
# Apply a lambda function to increase everyone's salary by 10%
df['Bonus Salary'] = df['Salary'].apply(lambda x: x * 1.10)
df

     Name  Age  Salary Department  Bonus Salary
0    Anas   19   50000         IT       55000.0
1    John   20   40000         HR       44000.0
2    Jack   25   35000         IT       38500.0
3     Sam   30   60000    Finance       66000.0
4  Hamdan   15   20000         HR       22000.0

## 7. Concatenation

In [13]:
data2 = {
    'Name': ['Emily', 'Michael'],
    'Age': [28, 35],
    'Salary': [55000, 70000],
    'Department': ['IT', 'Finance']
}
df2 = pd.DataFrame(data2)

# Append new rows to the existing DataFrame
df_concat = pd.concat([df, df2], ignore_index=True)
df_concat

      Name  Age  Salary Department  Bonus Salary
0     Anas   19   50000         IT       55000.0
1     John   20   40000         HR       44000.0
2     Jack   25   35000         IT       38500.0
3      Sam   30   60000    Finance       66000.0
4   Hamdan   15   20000         HR       22000.0
5    Emily   28   55000         IT           NaN
6  Michael   35   70000    Finance           NaN